### ISSUE TITLE
Gradle升级之后获取属性方法需要用ObjectFactory.listProperty

### ISSUE THREAD

**Issue by zhandroids** [nikeorever/SuperclassReplacemenGradlePlugin#2]
Please use the ObjectFactory.listProperty() method to create a property of type List<T>
`@Suppress("UnstableApiUsage")
open class CrashWebViews(project: Project) {
    @get:Input
    val qualifiedNames = project.objects.property<MutableList<String>>()
}
`
在LollipopCrashWebViewFixingPlugin.kt中

**Comment by nikeorever** [comment]
这个库废弃了，请使用这个库[reparatur](https://github.com/nikeorever/reparatur)
